CANDLE_INTERVAL_1MIN = '1m'
CANDLE_INTERVAL_1HOUR = '1h'
CANDLE_INTERVAL_4HOURS = '4h'
CANDLE_INTERVAL_6HOURS = '6h'
CANDLE_INTERVAL_12HOURS = '12h'
CANDLE_INTERVAL_1D = '1d'
CANDLE_INTERVAL_7D = '7d'
CANDLE_INTERVAL_30D = '1M'

SIDE_BUY = 'BUY'
SIDE_SELL = 'SELL'

ORDER_STATUS_PLACED = 'ORDER_STATUS_PLACED'
ORDER_STATUS_CLOSED = 'ORDER_STATUS_CLOSED'
ORDER_STATUS_CANCELLED = 'ORDER_STATUS_CANCELLED'

ORDER_TYPE_LIMIT = 'LIMIT'
ORDER_TYPE_MARKET = 'MARKET'

ORDER_CONDITION_GTC = 'GOOD_TILL_CANCELLED'
ORDER_CONDITION_IOC = 'IMMEDIATE_OR_CANCEL'
ORDER_CONDITION_FOK = 'FILL_OR_KILL'